-- Repository DONE
CREATE TABLE IF NOT EXISTS Staff
(
    id             integer primary key not null generated by default as identity,
    first_name     text                not null,
    last_name      text                not null,
    address        text,
    phone_res      varchar(10),
    phone_mob      varchar(10)         not null,
    enroll_date    date                not null,
    staff_role     integer references staffrole (id),
    direct_manager integer references staffrole (id)
);

-- Repository DONE
CREATE TABLE IF NOT EXISTS StaffRole
(
    id                integer primary key not null generated by default as identity,
    staff_role        text                not null,
    staff_description text                not null
);


-- Repository DONE
-- Service DONE
CREATE TABLE IF NOT EXISTS Customer
(
    id          integer primary key not null generated by default as identity,
    first_name  text                not null,
    last_name   text                not null,
    address     text,
    phone_res   varchar(10),
    phone_mob   varchar(10)         not null,
    enroll_date date,
    is_active   bool,
    created_by  integer references staff (id),
    created_on  date                not null,
    updated_by  integer default null,
    updated_on  date    default null
);

-- Repository DONE
CREATE TABLE IF NOT EXISTS MenuItems
(
    item_id     serial primary key,
    name        varchar(100)   not null,
    description text           not null,
    price       decimal(10, 2) not null,
    category    varchar(50)
);

-- Repository DONE
CREATE TABLE IF NOT EXISTS Orders
(
    order_id     serial primary key,
    customer_id  integer references Customer (id),
    order_date   date not null,
    table_number integer,
    total_amount decimal(10, 2)
);

-- Repository DONE
CREATE TABLE IF NOT EXISTS OrderItems
(
    order_item_id serial primary key,
    order_id      integer references Orders (order_id),
    item_id       integer references MenuItems (item_id),
    quantity      integer,
    subtotal      decimal(10, 2)
);

-- Repository DONE
CREATE TABLE IF NOT EXISTS Tables
(
    table_number integer primary key,
    capacity     integer,
    status       varchar(20)
);

-- Repository DONE
CREATE TABLE IF NOT EXISTS Reservations
(
    reservation_id   serial primary key,
    customer_id      integer references Customer (id),
    reservation_date date,
    table_number     integer,
    party_size       integer
);